lang: 再次更新一些漏翻以及优化语言
tangge233/PCL2 pull request #23
Opened 2024-08-16 07:03 UTC by SALTWOOD

2024-08-16 07:07 UTC, tangge233 approved these changes

2024-08-16 07:08 UTC, tangge233 commented
如果没什么要更改的就合了（

2024-08-16 07:08 UTC, allMagicNB commented
别急，我想看看

2024-08-16 07:31 UTC, allMagicNB requested changes
等会慢慢看

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangSetThemeNameBlue">龙猫蓝</s:String>
？

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangSetFuncHiddenToolTip">你可以让不需要的页面或特定功能拜拜。在随意界面按 F12 可以暂时显示拜拜的功能。</s:String>
```suggestion
    <s:String x:Key="LangSetFuncHiddenToolTip">你可以让不需要的页面或特定功能被雪藏。在随意界面按 F12 可以暂时挖出被雪藏的功能。</s:String>
```

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSpeedRightInstallOptiFineMethodA">安装 Opti不Fine（方式 A）</s:String>
```suggestion
    <s:String x:Key="LangPageSpeedRightGetOptiFineDownloadAddress">获取 高清不修复 下崽地址</s:String>
    <s:String x:Key="LangPageSpeedRightDownloadOptiFineMainFile">下崽 高清不修复 主文件</s:String>
    <s:String x:Key="LangPageSpeedRightInstallOptiFineMethodA">安装 高清不修复（方式 A）</s:String>
```
我还是更建议全中文。

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadBeta">战未来版</s:String>
```suggestion
    <s:String x:Key="LangDownloadBeta">易崩版</s:String>
```

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangDownloadAncientVersion">古代版</s:String>
```suggestion
    <s:String x:Key="LangDownloadAncientVersion">侏罗纪版</s:String>
```

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadRecommendForge">推荐铁砧版本：</s:String>
```suggestion
    <s:String x:Key="LangDownloadForgeIncompatible">不兼容锻造</s:String>
    <s:String x:Key="LangDownloadRecommendForge">推荐锻造版本：</s:String>
```
上边都用新锻造了，呼应下（

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadCompToCurseForge">转到诅咒铁砧</s:String>
```suggestion
    <s:String x:Key="LangDownloadCompToCurseForge">转到诅咒锻造</s:String>
```
这个我觉得结合用途翻还是锻造更好（

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadInstallFabricApi">你还没选择安装布料API，这会导致大多数 Mod 没办法使用！</s:String>
```suggestion
    <s:String x:Key="LangDownloadInstallFabricApi">你还没选择安装布料动态程序接口，这会导致大多数 Mod 原地螺旋升天爆炸！</s:String>
```

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadInstallOldOptiFabric">安装结束后，请在 Mod 下崽中搜索 高清布料 Origins 并下崽，否则 Opti不Fine 会没办法使用！</s:String>
```suggestion
    <s:String x:Key="LangDownloadInstallOptiFabric">你还没选择安装高清布料，这会导致高清不修复没办法使用！</s:String>
    <s:String x:Key="LangDownloadInstallOptiFine">高清不修复与一部分 Mod 的兼容性不佳，请谨慎安装。</s:String>
    <s:String x:Key="LangDownloadInstallOldOptiFabric">安装结束后，请在 Mod 下崽中搜索 高清布料 Origins 并下崽，否则高清不修复会没办法使用！</s:String>
```

2024-08-16 07:31 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadInstallOptiFineFabricNeed">需要 Opti不Fine 与布料</s:String>
```suggestion
    <s:String x:Key="LangDownloadInstallOptiFineNeed">需要高清不修复</s:String>
    <s:String x:Key="LangDownloadInstallOptiFineFabricNeed">需要高清不修复与布料</s:String>
```

2024-08-16 09:49 UTC, allMagicNB reviewed
UUID 改成身份证，列表改成名单。

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModLaunchExceptionReleaseJavaWrapperFail">释放 Jvav Wrapper 不成功，请查看平原合成发射台日志查找详细信息</s:String>
```suggestion
    <s:String x:Key="LangModLaunchExceptionReleaseJavaWrapperFail">释放 Jvav 擦腚纸不成功，请查看平原合成发射台日志查找详细信息</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModLaunchExceptionOnlineUUIDLenIncorrect">获取的正版 唯一识别身份证 长度不足（{0}）</s:String>
```suggestion
    <s:String x:Key="LangModLaunchExceptionOnlineUUIDGetFail">从官网获取正版身份证号不成功（{0}）</s:String>
    <s:String x:Key="LangModLaunchExceptionOnlineUUIDLenIncorrect">获取的正版身份证号长度不足（{0}）</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModLaunchDialogTitleGetSkinFail">皮肤获取不成功</s:String>
```suggestion
    <s:String x:Key="LangModLaunchDialogTitleGetSkinFail">外壳获取不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangModBaseDialogWebOpenFailTitle">没办法打开网页</s:String>
```suggestion
    <s:String x:Key="LangModBaseDialogWebOpenFailTitle">打不开网页</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModMinecraftExceptionEmptyUuid">UUID 是空的。</s:String>
```suggestion
    <s:String x:Key="LangModMinecraftExceptionEmptyUuid">身份证号是空的。</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModMinecraftExceptionEmptySkin">皮肤返回值是空的，可能是未设置自定义皮肤的运动员</s:String>
```suggestion
    <s:String x:Key="LangModMinecraftExceptionEmptySkin">外壳返回值是空的，可能是未设置自定义外壳的运动员</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModMinecraftExceptionSkinTypeInvalid">皮肤地址种类莫有效：{0}</s:String>
```suggestion
    <s:String x:Key="LangModMinecraftExceptionSkinTypeInvalid">外壳地址种类莫有效：{0}</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangModMinecraftExceptionSkinPropertyNotFound">未从皮肤返回值中找到符合条件的 Property</s:String>
```suggestion
    <s:String x:Key="LangModMinecraftExceptionSkinPropertyNotFound">未从外壳返回值中找到符合条件的 Property</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangModMinecraftExceptionSkinNoData">皮肤返回值中莫得皮肤数据项，可能是未设置自定义皮肤的运动员</s:String>
```suggestion
    <s:String x:Key="LangModMinecraftExceptionSkinNoData">外壳返回值中莫得外壳数据项，可能是未设置自定义外壳的运动员</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangModMinecraftExceptionSkinNotSet">运动员未设置自定义皮肤</s:String>
```suggestion
     <s:String x:Key="LangModMinecraftExceptionSkinNotSet">运动员未设置自定义外壳</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModEventOpeningWeb">在打开了，你先别急……</s:String>
```suggestion
    <s:String x:Key="LangModEventOpeningWeb">你先别急</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +如果你莫得修改相关文件，不要瞎勾选此项。</s:String>
```suggestion
如果你莫得修改相关文件，请嫑瞎勾选此项。</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> + · {uuid}：运动员的 唯一识别身份证
```suggestion
 · {uuid}：运动员的身份证号
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupSystemHintFinishDownloadTaskBeforeChangeLanguage">您先别急，等待下载任务结束再换语言……</s:String>
```suggestion
    <s:String x:Key="LangPageSetupSystemHintFinishDownloadTaskBeforeChangeLanguage">你先别急，等下载任务结束再换语言也不迟</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupSystemDownloadSSLToolTip">验证证书会提高安全性，但好像有概率登不上正版（#3018）。
```suggestion
    <s:String x:Key="LangPageSetupSystemDownloadSSLToolTip">验证证书会提高安全性，但好像有概率登不上正版（井三千零一十八）。
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupLaunchSkinEmptyFail">清空离线皮肤不成功</s:String>
```suggestion
    <s:String x:Key="LangPageSetupLaunchSkinEmptyFail">清空离线外壳不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupLaunchSkinChangeFail">改变离线皮肤不成功</s:String>
```suggestion
    <s:String x:Key="LangPageSetupLaunchSkinChangeFail">改变离线外壳不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> + · {uuid}：运动员的 唯一识别身份证
```suggestion
 · {uuid}：运动员的身份证号
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupLaunchLaunchGamePriorityHigh">高（优先保证游戏运行，游戏更丝滑，但可能造成其他程序卡顿）</s:String>
```suggestion
    <s:String x:Key="LangPageSetupLaunchLaunchGamePriorityHigh">高（优先保证游戏运行，游戏像吃了德芙一样丝滑，但可能造成其他程序卡顿）</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupLaunchLaunchVisibilityCloseOnGameClose">游戏发射后隐藏，游戏退出后自动帮你关掉</s:String>
```suggestion
    <s:String x:Key="LangPageSetupLaunchLaunchVisibilityCloseOnGameClose">游戏发射后雪藏，游戏退出后自动帮你关掉</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageLoginMsSkinChangeSkinFailByTimeOut">换皮肤不成功：与 Bugjump 皮肤服务器的连接超时，请检查你的网络是否通畅！</s:String>
```suggestion
    <s:String x:Key="LangPageLoginMsSkinChangeSkinFail">换外壳不成功</s:String>
    <s:String x:Key="LangPageLoginMsSkinChangeSkinFailByTimeOut">换外壳不成功：与 Bugjump 外壳服务器的连接超时，请检查你的网络是否通畅！</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangPageSetupLaunchLaunchVisibilityKeep">游戏发射后仍保持不变</s:String>
```suggestion
    <s:String x:Key="LangPageSetupLaunchLaunchVisibilityKeep">游戏发射后啥也不干</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageSetupLaunchLaunchVisibilityCloseOnGameStart">游戏发射后马上关掉</s:String>
```suggestion
    <s:String x:Key="LangPageSetupLaunchLaunchVisibilityCloseOnGameStart">游戏发射后马上紫砂</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangPageLoginMsSkinChangeSkinFailByLoginFail">登录不成功，没办法换掉皮肤！</s:String>
```suggestion
    <s:String x:Key="LangPageLoginMsSkinChangeSkinFailByLoginFail">登录不成功，没办法换掉外壳！</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangPageLoginAuthSkinChanging">正在尝试更换，等一下！</s:String>
```suggestion
    <s:String x:Key="LangPageLoginAuthSkinChanging">正在尝试更换，先等等！</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangLaunchRightLabHint1">快照版包含还没正式发布的测试功能，仅用于赞助者本人尝鲜。请不要发给其他人或者用来制作整合包哦！</s:String>
？还有一行呢？

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangLoginOAuthNoGithubLogin">平原合成发射台不支持使用 GayHub 登录巨硬账号！</s:String>
```suggestion
    <s:String x:Key="LangLoginOAuthNoGithubLogin">平原合成发射台不支持使用 GaytHub 登录巨硬账号！</s:String>
```
这是刻意的，为了消歧义。

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangMySkinCapeNameMapMaker">Realms 地图制作者海角</s:String>
```suggestion
    <s:String x:Key="LangMySkinCapeNameMapMaker">领域地图制作者海角</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangMySkinHintChangeCapeFail">换掉海角不成功</s:String>
```suggestion
    <s:String x:Key="LangMySkinHintChangeCapeFail">再婚海角不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangMySkinHintGettingCape">正在获取海角列表，等一下……</s:String>
```suggestion
    <s:String x:Key="LangMySkinHintGettingCape">正在获取海角列表，先别急……</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangMySkinHintRefreshFail">刷新皮肤缓存不成功</s:String>
```suggestion
    <s:String x:Key="LangMySkinHintRefreshFail">刷新外壳缓存不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangMySkinHintSaveFail">保存皮肤不成功</s:String>
```suggestion
    <s:String x:Key="LangMySkinHintSaveFail">保存外壳不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadOptiFineDesc">高清不修复又名低清不修复，它让你可以安装光影、使用高清材质，并且可以大幅提高游戏性能。</s:String>
```suggestion
    <s:String x:Key="LangDownloadOptiFineDesc">高清不修复又名 OptiNotFine，它让你可以安装光影、使用高清材质，并且可以大幅提高游戏性能。</s:String>
```
这边颠倒下原文。

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadInstallFailGetList">获取版本列表不成功：</s:String>
```suggestion
    <s:String x:Key="LangDownloadInstallFailGetListUnknwonStatus">获取版本名单不成功：未知错误，状态为</s:String>
    <s:String x:Key="LangDownloadInstallFailGetList">获取版本名单不成功：</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangDownloadInstallOldOptiFabric">安装结束后，请在 Mod 下崽中搜索 高清布料 Origins 并下崽，否则高清不修复会没办法使用！</s:String>
```suggestion
    <s:String x:Key="LangDownloadInstallOldOptiFabric">安装结束后，请在 Mod 下崽中搜索高清布料 Origins 并下崽，否则高清不修复会没办法使用！</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangHiddenModeFail">刷新功能拜拜项目不成功</s:String>
```suggestion
    <s:String x:Key="LangHiddenModeFail">刷新功能雪藏项目不成功</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangHiddenModeTitleB">功能拜拜</s:String>
```suggestion
    <s:String x:Key="LangHiddenModeTitleB">功能雪藏</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangHiddenModeTitleA">功能拜拜（已暂时关掉，按 F12 以重新启用）</s:String>
```suggestion
     <s:String x:Key="LangHiddenModeTitleA">功能雪藏（已暂时关掉，按 F12 以重新雪藏）</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangHiddenModeTitleA">功能拜拜（已暂时关掉，按 F12 以重新启用）</s:String>
```suggestion
     <s:String x:Key="LangHiddenModeTitleA">功能雪藏（已暂时挖出，按 F12 以重新雪藏）</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangHiddenModeTitleA">功能拜拜（已暂时关掉，按 F12 以重新启用）</s:String>
```suggestion
     <s:String x:Key="LangHiddenModeTitleA">功能雪藏（已暂时挖出，按 F12 以重新雪藏）</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangHiddenModeTitleA">功能拜拜（已暂时关掉，按 F12 以重新启用）</s:String>
```suggestion
     <s:String x:Key="LangHiddenModeTitleA">功能雪藏（已暂时挖出，按 F12 以重新雪藏）</s:String>
```

2024-08-16 09:49 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangSetFuncHiddenMoreSubPage">更多子页面</s:String>
```suggestion
    <s:String x:Key="LangSetFuncHiddenMoreSubPage">更多 子页面</s:String>
```

2024-08-16 09:50 UTC, allMagicNB requested changes

2024-08-16 09:50 UTC, allMagicNB commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangHiddenModeTitleA">功能拜拜（已暂时关掉，按 F12 以重新启用）</s:String>
```suggestion
     <s:String x:Key="LangHiddenModeTitleA">功能雪藏（已暂时挖出，按 F12 以重新雪藏）</s:String>
```

2024-08-17 07:13 UTC, tangge233 commented
来了（

2024-08-17 07:44 UTC, tangge233 requested changes
小问题，弄完后就可以合并了

2024-08-17 07:44 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangSetFuncHiddenToolTip">你可以让不需要的页面或特定功能被雪藏。在随意界面按 F12 可以暂时显示拜拜的功能。</s:String>
```suggestion
    <s:String x:Key="LangSetFuncHiddenToolTip">你可以让不需要的页面或特定功能被雪藏。在随意界面按 F12 可以暂时挖出被雪藏的功能。</s:String>
```

2024-08-17 07:44 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangLoginOAuthNoGithubLogin">平原合成发射台不支持使用 GaytHub 登录巨硬账号！</s:String>
怎么这里改掉了？之前不是 `GayHub` 么

2024-08-17 07:44 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModModpackExtraArchive">正在解压压缩包……</s:String>
此处 Key 值怎么修改了，如果需要修改需要同步其它地方一起的

2024-08-17 09:02 UTC, allMagicNB commented
……更改太多了 GitHub Mobile 看不了……

2024-08-17 15:08 UTC, SALTWOOD commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
>      <s:String x:Key="LangLoginOAuthNoGithubLogin">平原合成发射台不支持使用 GaytHub 登录巨硬账号！</s:String>
说是消歧义，GaytHub

2024-08-17 15:09 UTC, SALTWOOD commented on Plain Craft Launcher 2/Resources/Language/zh_MEME.xaml
> +    <s:String x:Key="LangModModpackExtraArchive">正在解压压缩包……</s:String>
Key改了，在另一个分支修复的，已经合并到主分支了所以也改了

2024-08-17 15:21 UTC, merged