Language overhaul 3
tangge233/PCL2 pull request #5
Opened 2024-07-10 09:36 UTC by 3gf8jv4dv

Continue with the overhaul of en-US. Hopefully this will be my last overhaul, with only minor revisions to follow.

Take some opinions from Chiloven945 ([Chiloven945@`509469b`](https://github.com/Chiloven945/PCL2/commit/509469be3b0c7e9df1646c0ab1c47d21647715d0)). Thanks!

2024-07-10 10:21 UTC, Chiloven945 commented
Thanks for taking my opinions! I will check it stat. and do more modification.

2024-07-10 11:05 UTC, tangge233 approved these changes
Nice work.

2024-07-10 11:40 UTC, Chiloven945 commented
I've done some new changes in my fork, sorry but I don't have enough time. I'll do more later.

2024-07-16 00:40 UTC, tangge233 requested changes
A small problem.

2024-07-16 00:40 UTC, tangge233 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +            Fresh.Info = If(Fresh.Info = "", GetLang("LangDownloadNewStable"), GetLang("LangDownloadNewStable"))
Why delete "Fresh.Info" here?

2024-07-16 00:40 UTC, tangge233 commented on Plain Craft Launcher 2/Pages/PageDownload/ModDownloadLib.vb
> +            Fresh.Info = If(Fresh.Info = "", GetLang("LangDownloadNewTest"), GetLang("LangDownloadNewTest"))
Also here

2024-07-16 01:26 UTC, tangge233 commented
I'm sorry, that was my mistake.Nothing wrong actually.

2024-07-16 01:26 UTC, merged