lang: 小修改
tangge233/PCL2 pull request #9
Opened 2024-07-25 12:16 UTC by wuyuncheng-26

2024-07-25 12:54 UTC, tangge233 requested changes
一个 Key 值小问题

2024-07-25 12:54 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/en_US.xaml
> +    <s:String x:Key="LangModSecretDialogNoTheme">This version does not include theme functionality...</s:String>
它应该是 Hint 而不是 Dialog…

2024-07-26 00:33 UTC, wuyuncheng-26 commented
先放一放吧，我还有其他要加的

2024-07-26 01:09 UTC, wuyuncheng-26 commented
![image](https://github.com/user-attachments/assets/5eaee70d-faa8-4440-a261-987fc393dd46)
？！我也遇到这种情况了

2024-07-26 01:27 UTC, tangge233 requested changes
Some suggestions

2024-07-26 01:27 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/en_US.xaml
> +    <s:String x:Key="LangModSecretHintNoTheme">This version does not include theme functionality...</s:String>
```suggestion
    <s:String x:Key="LangModSecretHintNoTheme">The current version of PCL does not include theme functionality...</s:String>
```
这样说的更清楚点

2024-07-26 01:27 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/en_US.xaml
> +    <s:String x:Key="LangModSecretHintNoUpdate">This version does not include update functionality...</s:String>
```suggestion
    <s:String x:Key="LangModSecretHintNoUpdate">The current version of PCL does not include update functionality...</s:String>
```

2024-07-26 01:27 UTC, tangge233 commented on Plain Craft Launcher 2/Resources/Language/en_US.xaml
> +    <s:String x:Key="LangPageOtherTestNoUtility">For ease of maintenance, the open source content does not include the utility function...</s:String>
```suggestion
    <s:String x:Key="LangPageOtherTestNoUtility">For ease of maintenance, the debug version does not include the utility function...</s:String>
```

2024-07-26 01:39 UTC, wuyuncheng-26 commented on Plain Craft Launcher 2/Resources/Language/en_US.xaml
> +    <s:String x:Key="LangPageOtherTestNoUtility">For ease of maintenance, the open source content does not include the utility function...</s:String>
hmmmm 开源内容翻译成这个？？？

2024-07-26 01:51 UTC, tangge233 commented
我刚刚去查看了下之前的翻译方式是 Open-Source…
非常抱歉弄错了一些信息

2024-07-26 01:53 UTC, merged